FROM silex/emacs
MAINTAINER dickmao
RUN set -xe \
  && apt-get -yq update \
  && DEBIAN_FRONTEND=noninteractive apt-get -yq install gettext-base dovecot-common dovecot-imapd vim less netcat-openbsd \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir $HOME/Maildir
COPY ${GMAIL_USER}.gpg /tmp/${GMAIL_USER}.gpg
COPY dot.authinfo /tmp/.authinfo
COPY dovecot.users /tmp/users
RUN \
     mv /tmp/${GMAIL_USER}.gpg $HOME/Maildir \
  && mv /tmp/.authinfo $HOME \
  && chmod 600 $HOME/.authinfo \
  && DOVECOT_UID=$(id -u $USER) DOVECOT_GID=$(id -g $USER) DOVECOT_HOME=$HOME envsubst < /tmp/users > /etc/dovecot/users \
  && chown root:dovecot /etc/dovecot/users \
  && chmod 640 /etc/dovecot/users \
  && chmod 600 $HOME/.authinfo \
  && sed -E -i 's|^#\s*(mail_debug).*|\1 = yes|' /etc/dovecot/conf.d/10-logging.conf \
  && sed -E -i 's|^#\s*(auth_debug).*|\1 = yes|' /etc/dovecot/conf.d/10-logging.conf \
  && sed -E -i 's|^#\s*(log_path).*|\1 = /var/log/dovecot.log|' /etc/dovecot/conf.d/10-loggin   g.conf \
  && sed -E -i 's|^#\s*(!include auth-passwdfile.*)|\1|' /etc/dovecot/conf.d/10-auth.conf \
  && sed -E -i 's|^\s*(mail_location).*|\1 = maildir:%h/Maildir/%n:LAYOUT=fs:INBOX=%h/Maildir/%n/Inbox|' /etc/dovecot/conf.d/10-mail.conf \
  && /etc/init.d/dovecot start  